model:
  n_neurons: 10

train:
  uid: ~
  lr: !!float 1e-2
  cycle_period: 5000
  cycle_mult: !!float 1.5
  min_lr: !!float 1e-8
  lr_decay: !!float 0.8
  
  ckpt_interval: 1
  patience: 5
  log_dir: logs
  epoch: 3
  eval_per_epoch: 1
  n_workers: 4
  
  deepspeed:
    train_micro_batch_size_per_gpu: 32
    gradient_accumulation_steps: 1
    zero_optimization:
      stage: 2

data:
  n_samples: 250000
  val_ratio: !!float 0.2

  